import { ImprovementCategory } from '../types';

export const improvementCategories: ImprovementCategory[] = [
  {
    id: 'captura-comercial',
    title: 'Captura comercial',
    accent: '#c27d22',
    state: 'Activa',
    items: [
      'Formulario con datos del cliente y validación básica.',
      'Captura del tipo de mueble desde el segundo cero.',
      'Registro del material principal requerido.',
      'Registro del tamaño del mueble en formato legible.',
      'Interruptor explícito para definir si incluye almohadas.',
      'Campo de costo estimado para la toma comercial.',
      'Fecha objetivo de entrega para compromisos tempranos.',
      'Notas comerciales para condiciones especiales.',
      'Generación automática de referencia única por pedido.',
      'Etiquetas automáticas por material y accesorios.',
      'Asignación inmediata del comercial responsable.',
      'Prioridad automática según cercanía de entrega.',
      'Resumen visual del pedido antes de enviarlo.',
      'Reseteo rápido del formulario tras crear la solicitud.',
      'Listado de nuevas solicitudes en el mismo panel.',
      'Vista de pedidos recientes para seguimiento comercial.',
      'Estructura preparada para multicliente por ciudad.',
      'Campos pensados para cotización y fabricación.',
      'Validación para evitar pedidos incompletos.',
      'Persistencia local de la operación comercial.',
      'Historial inicial del pedido desde su creación.',
      'Compatibilidad móvil y web del formulario.',
      'Diseño de alto contraste para lectura rápida.',
      'Texto guía contextual en los principales campos.',
      'Base lista para agregar adjuntos y medidas futuras.',
    ],
  },
  {
    id: 'orquestacion-admin',
    title: 'Orquestación administrativa',
    accent: '#0f766e',
    state: 'Activa',
    items: [
      'Aprobación administrativa explícita del pedido.',
      'Configuración del precio final al cliente.',
      'Cálculo automático del margen esperado.',
      'Edición del costo de producción desde administración.',
      'Notas administrativas internas por pedido.',
      'Asignación del usuario responsable por etapa.',
      'Reordenamiento del flujo productivo con botones.',
      'Definición del esquema de pago por etapa.',
      'Valor individual de ganancia para cada responsable.',
      'Control visual para etapas fijas y móviles.',
      'Selección de responsables por rol especializado.',
      'Compatibilidad con cambios de responsable en caliente.',
      'Bloque administrativo separado del comercial.',
      'Vista de pedidos pendientes por aprobar.',
      'Vista de pedidos activos que siguen editables.',
      'Etapa administrativa visible como nodo del flujo.',
      'Aprobación conectada con notificación automática.',
      'Preparación de estructura para reglas de negocio futuras.',
      'Edición del flujo sin perder historial del pedido.',
      'Reasignación útil ante ausencias del equipo.',
      'Modelo compatible con aprobaciones multiusuario.',
      'Soporte para reordenar producción por prioridad.',
      'Capacidad de revisar el detalle completo del pedido.',
      'Persistencia de cambios administrativos entre sesiones.',
      'Base lista para autorizaciones y firmas posteriores.',
    ],
  },
  {
    id: 'ejecucion-produccion',
    title: 'Ejecución de producción',
    accent: '#184e77',
    state: 'Activa',
    items: [
      'Flujo secuencial que respeta el orden definido.',
      'Nodos del proceso con color por estado.',
      'Avatares por usuario para leer el flujo rápido.',
      'Estados diferenciados: pendiente, activo, completado y bloqueado.',
      'Acción de iniciar etapa para el responsable actual.',
      'Acción de finalizar etapa para el responsable actual.',
      'Bloqueo natural de etapas futuras hasta liberar la previa.',
      'Cambio del estado global del pedido según avance real.',
      'Cálculo automático del progreso porcentual.',
      'Detalle del responsable asignado por etapa.',
      'Registro de hora de inicio por etapa.',
      'Registro de hora de finalización por etapa.',
      'Notas operativas por cada tramo del flujo.',
      'Panel de etapa actual desbloqueada.',
      'Compatibilidad con flujo extendido de fabricación.',
      'Base para retrabajos o etapas adicionales.',
      'Historial de eventos encadenado a la producción.',
      'Indicador de pedido completado al cerrar la última etapa.',
      'Vista pensada para supervisión en piso de planta.',
      'Colorimetría funcional para saber quién sigue.',
      'Resumen del estado general por pedido.',
      'Lectura horizontal del flujo estilo línea de producción.',
      'Preparación para cronometraje y tiempos estándar.',
      'Capacidad de continuar procesos en sesiones posteriores.',
      'Preparación para alertas por cuellos de botella.',
    ],
  },
  {
    id: 'calidad-logistica',
    title: 'Calidad y logística',
    accent: '#3d405b',
    state: 'Activa',
    items: [
      'Etapa dedicada de control de calidad.',
      'Etapa dedicada de despacho o entrega.',
      'Capacidad de reasignar calidad y despacho.',
      'Monitoreo del pedido hasta el cierre total.',
      'Preparación de checklist de inspección por etapa.',
      'Base para evidencias fotográficas de salida.',
      'Preparación para registrar incidencias logísticas.',
      'Resumen de hitos antes de entrega.',
      'Indicador visual de pedidos listos para salida.',
      'Notas finales para cliente o transporte.',
      'Compatibilidad con rutas de despacho futuras.',
      'Estructura para fecha real de entrega.',
      'Base para transportista y guía.',
      'Preparación para auditoría postproducción.',
      'Capacidad de activar doble revisión de calidad.',
      'Historial final del pedido hasta despacho.',
      'Visibilidad transversal del estado final.',
      'Preparación para firma de recibido.',
      'Soporte para observaciones de conformidad.',
      'Base para devoluciones o garantías.',
      'Lectura rápida de pedidos listos para cerrar.',
      'Panel útil para coordinadores de salida.',
      'Preparación para empaques y accesorios.',
      'Modelo extensible a instaladores externos.',
      'Espacio lógico para servicios posventa.',
    ],
  },
  {
    id: 'notificaciones',
    title: 'Notificaciones y alertas',
    accent: '#c94d3f',
    state: 'Activa',
    items: [
      'Centro de notificaciones dentro de la app.',
      'Clasificación por prioridad alta, media o baja.',
      'Etiquetas de canal por notificación.',
      'Marcado de lectura individual.',
      'Indicador de notificaciones no leídas.',
      'Creación automática de alerta al crear un pedido.',
      'Creación automática de alerta al aprobar un pedido.',
      'Creación automática de alerta al iniciar una etapa.',
      'Creación automática de alerta al finalizar una etapa.',
      'Preparación para recordatorios por vencimiento.',
      'Preferencia de escalamiento por horas.',
      'Configuración de digest diario.',
      'Bandera para priorizar push de eventos críticos.',
      'Soporte para canales Push, Email, In-app y WhatsApp.',
      'Notificación local nativa en dispositivos compatibles.',
      'Mensajes contextualizados con referencia de pedido.',
      'Receptores explícitos para cada evento.',
      'Base lista para disparos desde Firebase.',
      'Búsqueda de alertas por texto.',
      'Panel preparado para filtros posteriores.',
      'Feedback visual tras cada transición de estado.',
      'Historial centralizado para seguimiento.',
      'Compatibilidad con alertas de SLA futuras.',
      'Modelo preparado para plantillas por evento.',
      'Visibilidad operativa de incidencias pendientes.',
    ],
  },
  {
    id: 'cliente-documentos',
    title: 'Cliente y documentos',
    accent: '#8d5a97',
    state: 'Activa',
    items: [
      'Panel para comunicación con cliente.',
      'Resumen ejecutivo del pedido antes de enviar.',
      'Generación de PDF desde la app.',
      'PDF con datos del cliente y del mueble.',
      'PDF con precio final y progreso actual.',
      'Botón para compartir el PDF.',
      'Botón para preparar correo con el PDF adjunto en nativo.',
      'Fallback web por enlace mailto.',
      'Registro del cliente con nombre, correo, teléfono y ciudad.',
      'Texto de correo prearmado con contexto del pedido.',
      'Notificación automática al generar un documento.',
      'Preparación para historial de correos enviados.',
      'Base para plantillas de cotización.',
      'Base para plantillas de avance de producción.',
      'Preparación para acuse de recibo del cliente.',
      'Diseño de PDF amigable para impresión.',
      'Integración con impresión del sistema en web.',
      'Compatibilidad con flujos de aprobación documental.',
      'Preparación para firma digital futura.',
      'Texto de seguimiento listo para comercial.',
      'Estructura para anexar condiciones comerciales.',
      'Capacidad de enviar resumen aunque el pedido siga activo.',
      'Detalle de almohadas y especificaciones dentro del PDF.',
      'Preparación para compartir por apps compatibles.',
      'Base para cronología documental por pedido.',
    ],
  },
  {
    id: 'analitica',
    title: 'Analítica y control',
    accent: '#577590',
    state: 'Activa',
    items: [
      'Tarjetas KPI en el dashboard principal.',
      'Conteo de pedidos activos.',
      'Conteo de pedidos por aprobar.',
      'Conteo de pedidos bloqueados o en riesgo.',
      'Cálculo de margen promedio.',
      'Estimación del siguiente pago del equipo.',
      'Top de carga por colaborador.',
      'Vista de avance porcentual por pedido.',
      'Visualización de urgencias por vencimiento.',
      'Diferenciación por prioridad de negocio.',
      'Resumen rápido de pedidos completados.',
      'Base para comparar costos estimados y reales.',
      'Preparación para productividad por etapa.',
      'Preparación para tableros de cumplimiento.',
      'Preparación para métricas por comercial.',
      'Preparación para métricas por operario.',
      'Preparación para aging de pedidos.',
      'Panel de resumen pensado para dirección.',
      'Compatibilidad con filtros futuros por material.',
      'Compatibilidad con filtros futuros por ciudad.',
      'Base lista para exportes analíticos.',
      'Cálculos sin dependencia obligatoria de backend.',
      'Tarjetas compactas aptas para móvil.',
      'Señalización de foco operativo del día.',
      'Estructura para inteligencia de costos posterior.',
    ],
  },
  {
    id: 'ux',
    title: 'UX y diseño',
    accent: '#264653',
    state: 'Activa',
    items: [
      'Dirección visual cálida inspirada en taller y acabados.',
      'Fondo con gradientes y capas, no plano.',
      'Tarjetas con jerarquía clara y contraste alto.',
      'Uso consistente de colores semánticos.',
      'Navegación por pestañas internas de acceso rápido.',
      'Layout adaptable a móvil y web.',
      'Ancho controlado para lectura cómoda en pantallas grandes.',
      'Chips de rol para simular permisos operativos.',
      'Paneles segmentados por dominio funcional.',
      'Resumen visual en la cabecera de la app.',
      'Acciones principales visibles sin menús profundos.',
      'Componentes pensados para tocar con el dedo.',
      'Estados vacíos convertidos en señales de avance.',
      'Etiquetas compactas para información secundaria.',
      'Densidad visual optimizada para operación diaria.',
      'Jerarquía tipográfica clara en títulos y métricas.',
      'Tarjetas de flujo legibles en desplazamiento horizontal.',
      'Visualización rápida de responsables del pedido.',
      'Campos agrupados por intención y no por tecnicismo.',
      'Compatibilidad con teclado en formularios extensos.',
      'Búsqueda diferida para listas más fluidas.',
      'Diseño útil tanto para comercial como para planta.',
      'Componentes reutilizables de estilo consistente.',
      'Separación clara entre información y acción.',
      'Preparación para animaciones y microinteracciones posteriores.',
    ],
  },
  {
    id: 'seguridad-datos',
    title: 'Seguridad y datos',
    accent: '#6d597a',
    state: 'Preparada',
    items: [
      'Persistencia local con AsyncStorage.',
      'Estructura serializable para sincronización remota.',
      'Separación de tipos de dominio en TypeScript.',
      'Normalización de fechas en formato ISO.',
      'Base lista para auditoría de acciones.',
      'Roles definidos a nivel de dominio.',
      'Preparación para reglas de Firestore.',
      'Preparación para autenticación Firebase.',
      'Preparación para control de acceso por rol.',
      'Preparación para trazabilidad de cambios.',
      'Preparación para snapshots de respaldo.',
      'Preparación para colecciones separadas por dominio.',
      'Preparación para multiworkspace.',
      'Preparación para borrado lógico.',
      'Preparación para versionado de pedidos.',
      'Preparación para historial de sincronización.',
      'Preparación para alertar conflictos de datos.',
      'Preparación para lotes de escritura remota.',
      'Preparación para reglas con usuarios autenticados.',
      'Preparación para claims personalizados por rol.',
      'Preparación para anexos en Firebase Storage.',
      'Preparación para cifrado de datos sensibles en backend.',
      'Preparación para backups automatizados.',
      'Preparación para observabilidad de integraciones.',
      'Base consistente para crecer a producción.',
    ],
  },
  {
    id: 'firebase-colaboracion',
    title: 'Firebase y colaboración',
    accent: '#ff6b35',
    state: 'Preparada',
    items: [
      'Módulo de configuración Firebase por variables públicas.',
      'Inicialización segura solo si la configuración existe.',
      'Carga remota de empleados desde Firestore.',
      'Carga remota de pedidos desde Firestore.',
      'Carga remota de notificaciones desde Firestore.',
      'Escritura por lotes hacia colecciones principales.',
      'Marca de última sincronización visible.',
      'Fallback limpio a almacenamiento local.',
      'Seeding inicial cuando la nube esté vacía.',
      'Documento de settings preparado para la nube.',
      'Reglas de Firestore incluidas en el repositorio.',
      'Índices base de Firestore incluidos.',
      'firebase.json listo para despliegue.',
      'Función base para cola de correos incluida.',
      'Guía de despliegue Firebase documentada.',
      'Plantilla `.env` para las claves del proyecto.',
      'Capacidad de compartir el mismo estado con múltiples usuarios.',
      'Preparación para realtime listeners.',
      'Preparación para Cloud Functions con email.',
      'Preparación para colas de PDF y documentos.',
      'Preparación para extensiones oficiales de email.',
      'Preparación para Storage y adjuntos.',
      'Preparación para push remoto con Expo/Firebase.',
      'Preparación para sincronización operacional real.',
      'Puente listo para pasar de demo a producto operativo.',
    ],
  },
];

export const totalImprovements = improvementCategories.reduce(
  (total, category) => total + category.items.length,
  0,
);
